export const dynamic = 'force-dynamic';

import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/lib/providers/next-theme-provider';
import { DM_Sans } from 'next/font/google';
import { cn } from '@/lib/utils';

const inter = DM_Sans({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isServer = typeof window === 'undefined';

  return (
    <html lang="en" className={isServer ? 'dark' : ''} suppressHydrationWarning>

      <body className={cn('bg-background', inter.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
